CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    CONSTRAINT uq_role_code UNIQUE (code)
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    img VARCHAR(500),
    gender VARCHAR(5) NOT NULL,
    code VARCHAR(150) NOT NULL,
    rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
    CONSTRAINT uq_category_code UNIQUE (code)
);

CREATE INDEX idx_category_gender ON category (gender);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES category (id),
    name VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    price NUMERIC(12, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
    sell_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_product_name UNIQUE (name)
);

CREATE INDEX idx_product_category_id ON product (category_id);
CREATE INDEX idx_product_price ON product (price);
CREATE INDEX idx_product_rating ON product (rating);

CREATE TABLE product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    url VARCHAR(500) NOT NULL,
    image_index INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_product_image_product_id ON product_image (product_id);
