CREATE TABLE store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    tax_no VARCHAR(20) NOT NULL,
    bank_account VARCHAR(34) NOT NULL,
    CONSTRAINT uq_store_tax_no UNIQUE (tax_no),
    CONSTRAINT uq_store_bank_account UNIQUE (bank_account)
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role_id BIGINT NOT NULL REFERENCES role (id),
    store_id BIGINT REFERENCES store (id),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT uq_app_user_store UNIQUE (store_id)
);

CREATE INDEX idx_app_user_role_id ON app_user (role_id);
CREATE INDEX idx_app_user_store_id ON app_user (store_id);