CREATE TABLE customer_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user (id),
    address_id BIGINT NOT NULL,
    order_date TIMESTAMP WITH TIME ZONE NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_customer_order_price CHECK (price >= 0)
);

CREATE INDEX idx_customer_order_user_id ON customer_order (user_id);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES customer_order (id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product (id),
    count INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    detail VARCHAR(500),
    CONSTRAINT ck_order_item_count CHECK (count > 0)
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);
