spring:
  application:
    name: ecommerce-api
  profiles:
    default: local
  jpa:
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}
