spring:
  application:
    name: ecommerce-api
  profiles:
    default: local
  jpa:
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:db/migration

server:
  port: ${PORT:8080}
