-- Test-only table used solely to prove Flyway + JPA startup; never applied to production schema.
CREATE TABLE IF NOT EXISTS system_probe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note VARCHAR(255) NOT NULL,
    checked_at TIMESTAMP WITH TIME ZONE NOT NULL
);